"""
Agent Workforce — Knowledge Distiller

从 trace 数据蒸馏长期记忆，写入 knowledge/ 目录。
三层架构: traces (原始) → knowledge (蒸馏) → Claude Memory (索引)

用法:
  python3 evolution/distill_knowledge.py                    # dry-run
  python3 evolution/distill_knowledge.py --apply            # 写入 knowledge/
  python3 evolution/distill_knowledge.py --apply --scope weekly
"""

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
from trace_schema import _load_project_routes

CST = timezone(timedelta(hours=8))
AW_DIR = Path.home() / "agent-workforce"
TRACES_DIR = AW_DIR / "traces"
KNOWLEDGE_DIR = AW_DIR / "knowledge"


def load_all_traces() -> list[dict]:
    traces = []
    for f in sorted(TRACES_DIR.glob("2026-*.jsonl")):
        for line in f.read_text().strip().split("\n"):
            if line.strip():
                traces.append(json.loads(line))
    return traces


def distill_agent_profiles(traces: list[dict]) -> dict[str, str]:
    """蒸馏 Agent 能力档案 → knowledge/agents/*.yaml"""
    by_agent = defaultdict(lambda: {
        "count": 0, "golden": 0, "bad": 0, "fine": 0,
        "violations": 0, "files": Counter(), "projects": Counter(),
        "retry_traces": [], "golden_traces": [],
    })

    for t in traces:
        a = t.get("agent_profile", "").replace("_v1.0", "")
        if not a or a == "unknown":
            continue
        d = by_agent[a]
        d["count"] += 1
        af = t.get("auto_feedback", 3)
        if af == 4:
            d["golden"] += 1
            d["golden_traces"].append(t.get("trace_id", ""))
        elif af == 2:
            d["fine"] += 1
        elif af <= 1:
            d["bad"] += 1
            d["retry_traces"].append(t.get("trace_id", ""))
        if t.get("boundary_violations"):
            d["violations"] += 1
        for f in t.get("files_modified", []):
            d["files"][os.path.basename(f)] += 1
        d["projects"][t.get("project", "unknown")] += 1

    outputs = {}
    for agent, d in sorted(by_agent.items(), key=lambda x: -x[1]["count"]):
        if d["count"] < 3:
            continue

        golden_pct = d["golden"] * 100 // d["count"] if d["count"] else 0
        bad_pct = d["bad"] * 100 // d["count"] if d["count"] else 0
        top_files = d["files"].most_common(8)
        top_projects = d["projects"].most_common(5)

        yaml_lines = [
            f"# Auto-generated by distill_knowledge.py",
            f"# Last updated: {datetime.now(CST).strftime('%Y-%m-%d %H:%M')}",
            f"",
            f"agent: {agent}",
            f"total_tasks: {d['count']}",
            f"",
            f"scores:",
            f"  golden_rate: {golden_pct}%",
            f"  fine_rate: {d['fine'] * 100 // d['count']}%",
            f"  bad_rate: {bad_pct}%",
            f"  boundary_violations: {d['violations']}",
            f"",
            f"projects:",
        ]
        for proj, cnt in top_projects:
            yaml_lines.append(f"  - {proj}: {cnt}")

        yaml_lines.extend([
            f"",
            f"hot_files:",
        ])
        for fname, cnt in top_files:
            yaml_lines.append(f"  - \"{fname}\": {cnt}")

        yaml_lines.extend([
            f"",
            f"# Strengths: extracted from {d['golden']} golden traces",
            f"# Weaknesses: extracted from {d['bad']} bad + {d['fine']} fine traces",
            f"# Violations: {d['violations']} boundary violations detected",
        ])

        outputs[agent] = "\n".join(yaml_lines)

    return outputs


def distill_project_profiles(traces: list[dict]) -> dict[str, str]:
    """蒸馏项目经验 → knowledge/projects/*.yaml"""
    by_proj = defaultdict(lambda: {
        "count": 0, "golden": 0, "bad": 0, "fine": 0,
        "files": Counter(), "agents": Counter(),
        "retry_chains": 0, "dates": set(),
    })

    for t in traces:
        p = t.get("project", "unknown")
        if p == "unknown":
            continue
        d = by_proj[p]
        d["count"] += 1
        af = t.get("auto_feedback", 3)
        if af == 4:
            d["golden"] += 1
        elif af == 2:
            d["fine"] += 1
        elif af <= 1:
            d["bad"] += 1
        for f in t.get("files_modified", []):
            d["files"][os.path.basename(f)] += 1
        d["agents"][t.get("agent_profile", "").replace("_v1.0", "")] += 1
        day = t.get("timestamp", "")[:10]
        if day:
            d["dates"].add(day)

    # Count retry chains per project
    prev_proj = None
    chain = 0
    for t in traces:
        p = t.get("project", "unknown")
        goal = t.get("goal", "")
        is_retry = any(k in goal for k in ["还是", "不行", "再试", "503"])
        if p == prev_proj and is_retry:
            chain += 1
        else:
            if chain >= 2 and prev_proj and prev_proj != "unknown":
                by_proj[prev_proj]["retry_chains"] += 1
            chain = 0
        prev_proj = p

    outputs = {}
    for proj, d in sorted(by_proj.items(), key=lambda x: -x[1]["count"]):
        if d["count"] < 3:
            continue

        golden_pct = d["golden"] * 100 // d["count"] if d["count"] else 0
        top_files = d["files"].most_common(10)
        top_agents = d["agents"].most_common(3)
        active_days = sorted(d["dates"])

        yaml_lines = [
            f"# Auto-generated by distill_knowledge.py",
            f"# Last updated: {datetime.now(CST).strftime('%Y-%m-%d %H:%M')}",
            f"",
            f"project: {proj}",
            f"total_tasks: {d['count']}",
            f"active_days: {len(active_days)}",
            f"date_range: \"{active_days[0] if active_days else '?'} ~ {active_days[-1] if active_days else '?'}\"",
            f"",
            f"health:",
            f"  golden_rate: {golden_pct}%",
            f"  bad_count: {d['bad']}",
            f"  fine_count: {d['fine']}",
            f"  retry_chains: {d['retry_chains']}",
            f"",
            f"agents:",
        ]
        for agent, cnt in top_agents:
            yaml_lines.append(f"  - {agent}: {cnt}")

        yaml_lines.extend([
            f"",
            f"critical_files:",
        ])
        for fname, cnt in top_files:
            yaml_lines.append(f"  - \"{fname}\": {cnt}")

        outputs[proj] = "\n".join(yaml_lines)

    return outputs


def distill_patterns(traces: list[dict]) -> dict[str, str]:
    """蒸馏模式库 → knowledge/patterns/*.yaml"""
    patterns = {}

    # Pattern 1: Retry chain analysis
    retry_examples = []
    prev = None
    chain_traces = []
    for t in traces:
        goal = t.get("goal", "")
        is_retry = any(k in goal for k in ["还是", "不行", "再���", "503", "你再"])
        if is_retry:
            chain_traces.append(t.get("trace_id", ""))
        else:
            if len(chain_traces) >= 2:
                retry_examples.append({
                    "project": prev.get("project") if prev else "?",
                    "length": len(chain_traces),
                    "traces": chain_traces[:3],
                })
            chain_traces = []
        prev = t

    if retry_examples:
        total_retries = sum(e["length"] for e in retry_examples)
        patterns["retry_chains"] = "\n".join([
            "# Auto-generated pattern: Retry Chain Anti-Pattern",
            f"# Last updated: {datetime.now(CST).strftime('%Y-%m-%d %H:%M')}",
            "",
            "pattern: retry_chain",
            "type: anti-pattern",
            f"occurrences: {len(retry_examples)}",
            f"total_retries: {total_retries}",
            "",
            "description: |",
            "  用户连续说'还是不行'/'再试试' 形成的重试链。",
            "  根因通常是 Agent 没有建立完整的问题模型就开始修改。",
            "",
            "signal:",
            "  - \"用户 goal 包含: 还是/不���/再试/503\"",
            "  - \"同文件修改 3+ 次\"",
            "  - \"网络检查命令 > 5 次\"",
            "",
            "fix:",
            "  - \"停下来，先画出完整的系统拓扑或调用链\"",
            "  - \"Read 完整文件，理解上下游依赖\"",
            "  - \"一次性跑完整验证套件，不要逐条试\"",
            "",
            "examples:",
        ])
        for e in retry_examples[:5]:
            patterns["retry_chains"] += f"\n  - project: {e['project']}, length: {e['length']}, traces: {e['traces']}"

    # Pattern 2: Boundary violations
    violation_agents = Counter()
    violation_files = Counter()
    for t in traces:
        bv = t.get("boundary_violations", [])
        if bv:
            agent = t.get("agent_profile", "").replace("_v1.0", "")
            violation_agents[agent] += 1
            for f in bv:
                violation_files[f] += 1

    if violation_agents:
        patterns["boundary_violations"] = "\n".join([
            "# Auto-generated pattern: File Boundary Violations",
            f"# Last updated: {datetime.now(CST).strftime('%Y-%m-%d %H:%M')}",
            "",
            "pattern: boundary_violation",
            "type: anti-pattern",
            f"total_violations: {sum(violation_agents.values())}",
            "",
            "description: |",
            "  Agent 修改了其能力域外的文件类型。",
            "  通常因为 session 跨越了多个项目，或路由错误。",
            "",
            "by_agent:",
        ])
        for agent, cnt in violation_agents.most_common():
            patterns["boundary_violations"] += f"\n  - {agent}: {cnt}"
        patterns["boundary_violations"] += "\n\nfrequent_violations:"
        for fname, cnt in violation_files.most_common(10):
            patterns["boundary_violations"] += f"\n  - \"{fname}\": {cnt}"

    # Pattern 3: Golden trace patterns (what works well)
    golden = [t for t in traces if t.get("auto_feedback") == 4 and t.get("files_modified")]
    if golden:
        golden_efficiency = []
        for t in golden:
            fm = len(t.get("files_modified", []))
            tc = t.get("tool_call_count", 0)
            if fm > 0 and tc > 0:
                golden_efficiency.append(tc / fm)

        avg_eff = sum(golden_efficiency) / len(golden_efficiency) if golden_efficiency else 0
        patterns["golden_execution"] = "\n".join([
            "# Auto-generated pattern: Golden Execution",
            f"# Last updated: {datetime.now(CST).strftime('%Y-%m-%d %H:%M')}",
            "",
            "pattern: golden_execution",
            "type: workflow",
            f"golden_count: {len(golden)}",
            "",
            "description: |",
            "  从 golden trace 中提炼的高效执行特征。",
            "",
            "characteristics:",
            f"  avg_tool_calls_per_file: {avg_eff:.1f}",
            "  retry_edits: 0",
            "  common_traits:",
            "    - \"先 Read 目标文件，再精准 Edit\"",
            "    - \"工具调用 <= 5 次/文件\"",
            "    - \"无重复编辑同一文件\"",
            "    - \"对话轮次 <= 1\"",
        ])

    return patterns


def _extract_agent_lessons(traces: list[dict]) -> dict[str, list[dict]]:
    """
    从 trace 中提取结构化 lessons 写入 SQLite。
    每条 lesson 带 citations (文件引用) 和 importance。
    """
    lessons = defaultdict(list)

    # Group traces by agent
    by_agent = defaultdict(list)
    for t in traces:
        a = t.get("agent_profile", "").replace("_v1.0", "")
        if a and a != "unknown":
            by_agent[a].append(t)

    for agent, agent_traces in by_agent.items():
        # Lesson 1: hot files (修改频率最高的文件 = 核心文件)
        file_counts = Counter()
        file_projects = {}
        for t in agent_traces:
            for f in t.get("files_modified", []):
                fname = os.path.basename(f)
                file_counts[fname] += 1
                file_projects[fname] = t.get("project", "")

        for fname, cnt in file_counts.most_common(5):
            if cnt >= 3:
                lessons[agent].append({
                    "id": f"hotfile_{fname.replace('.', '_')}",
                    "content": f"核心文件: {fname} (修改 {cnt} 次)。修改前务必 Read 完整文件理解上下文。",
                    "project": file_projects.get(fname, ""),
                    "citations": [{"file": fname}],
                    "traces": [t.get("trace_id") for t in agent_traces if fname in str(t.get("files_modified", []))][:3],
                    "importance": min(0.9, 0.5 + cnt * 0.05),
                })

        # Lesson 2: retry patterns (同一个 agent 的重试 = 能力弱项)
        retry_traces = [t for t in agent_traces if t.get("auto_feedback") == 2]
        if len(retry_traces) >= 2:
            retry_projects = Counter(t.get("project") for t in retry_traces)
            top_proj = retry_projects.most_common(1)[0][0] if retry_projects else ""
            lessons[agent].append({
                "id": "retry_weakness",
                "content": f"弱项信号: {len(retry_traces)} 次 fine 评分，主要在 {top_proj}。重试链出现时应先 Read 完整文件+画调用链，不要逐步 trial-and-error。",
                "project": top_proj,
                "traces": [t.get("trace_id") for t in retry_traces[:5]],
                "importance": 0.75,
            })

        # Lesson 3: boundary violations
        violation_traces = [t for t in agent_traces if t.get("boundary_violations")]
        if violation_traces:
            bad_files = Counter()
            for t in violation_traces:
                for f in t.get("boundary_violations", []):
                    bad_files[f] += 1

            lessons[agent].append({
                "id": "boundary_warning",
                "content": f"边界警告: {len(violation_traces)} 次越界修改。禁止修改的文件类型: {', '.join(f for f,_ in bad_files.most_common(5))}",
                "traces": [t.get("trace_id") for t in violation_traces[:3]],
                "importance": 0.85,
            })

        # Lesson 4: golden patterns (高效执行的特征)
        golden_traces = [t for t in agent_traces if t.get("auto_feedback") == 4 and t.get("files_modified")]
        if len(golden_traces) >= 3:
            avg_tc = sum(t.get("tool_call_count", 0) for t in golden_traces) / len(golden_traces)
            avg_fm = sum(len(t.get("files_modified", [])) for t in golden_traces) / len(golden_traces)
            lessons[agent].append({
                "id": "golden_pattern",
                "content": f"高效模式: {len(golden_traces)} 次 golden。平均 {avg_tc:.0f} 次工具调用改 {avg_fm:.1f} 个文件 (效率比 {avg_tc/max(avg_fm,1):.1f})。",
                "traces": [t.get("trace_id") for t in golden_traces[:3]],
                "importance": 0.7,
            })

    return lessons


def main():
    parser = argparse.ArgumentParser(description="Distill traces into long-term knowledge")
    parser.add_argument("--apply", action="store_true", help="Actually write files")
    parser.add_argument("--scope", choices=["daily", "weekly", "full"], default="full")
    args = parser.parse_args()

    traces = load_all_traces()
    print(f"Loaded {len(traces)} traces\n")

    # 1. Agent profiles
    agent_profiles = distill_agent_profiles(traces)
    print(f"=== Agent Profiles ({len(agent_profiles)}) ===")
    for agent, content in agent_profiles.items():
        path = KNOWLEDGE_DIR / "agents" / f"{agent}.yaml"
        print(f"  {agent}: {content.count(chr(10))+1} lines → {path.name}")
        if args.apply:
            path.write_text(content + "\n")

    # 2. Project profiles
    project_profiles = distill_project_profiles(traces)
    print(f"\n=== Project Profiles ({len(project_profiles)}) ===")
    for proj, content in project_profiles.items():
        path = KNOWLEDGE_DIR / "projects" / f"{proj}.yaml"
        print(f"  {proj}: {content.count(chr(10))+1} lines → {path.name}")
        if args.apply:
            path.write_text(content + "\n")

    # 3. Patterns
    patterns = distill_patterns(traces)
    print(f"\n=== Patterns ({len(patterns)}) ===")
    for name, content in patterns.items():
        path = KNOWLEDGE_DIR / "patterns" / f"{name}.yaml"
        print(f"  {name}: {content.count(chr(10))+1} lines → {path.name}")
        if args.apply:
            path.write_text(content + "\n")

    # 4. Write to SQLite memory.db
    if args.apply:
        from memory_db import MemoryDB
        db = MemoryDB()

        db_count = 0

        # Agent lessons → SQLite
        for agent, data in _extract_agent_lessons(traces).items():
            for lesson in data:
                db.save(
                    type="lesson",
                    id=f"agent_{agent}_{lesson['id']}",
                    content=lesson["content"],
                    project=lesson.get("project", ""),
                    agent=agent,
                    citations=lesson.get("citations", []),
                    source_traces=lesson.get("traces", []),
                    importance=lesson.get("importance", 0.6),
                    tags=f"agent,{agent}",
                )
                db_count += 1

        # Pattern lessons → SQLite
        for name, content in patterns.items():
            db.save(
                type="pattern",
                id=f"pattern_{name}",
                content=content,
                importance=0.8,
                tags=f"pattern,{name}",
            )
            db_count += 1

        # Project hot files → SQLite
        for proj, content in project_profiles.items():
            db.save(
                type="project_profile",
                id=f"project_{proj}",
                content=content,
                project=proj,
                importance=0.7,
                tags=f"project,{proj}",
            )
            db_count += 1

        db.close()
        print(f"\n=== SQLite memory.db ===")
        print(f"  写入 {db_count} 条记忆")

    if not args.apply:
        print(f"\n[DRY-RUN] 加 --apply 参数实际写入")
    else:
        yaml_count = len(agent_profiles) + len(project_profiles) + len(patterns)
        print(f"\n[DONE] 写入 {yaml_count} 个 YAML + SQLite memory.db")


if __name__ == "__main__":
    main()
